# Site settings
title: CV - Luan S. Quaresma
description: Luan Quaresma
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Luan S. Quaresma
user_description: Olá me chamo Luan S. Quaresma e sou graduado em Ciência da Computação na faculdade Estácio|CEUT. Tenho paixão por tecnologia e como ajudar tanto a rotina cotidiano pessoal e profissional. Estou compartilhando minha experiencia e conhecimento nesse CV online.
user_title: Cientista da computação 
email: luansoares2010@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: 
# facebook_username: 
linkedin_username: luanfour
github_username:  luanfour
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
