# Site settings
title: Luan Quaresma
description: Luan Quaresma . io
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# domain: luanfour.github.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
# url: https://luansq.github.io/ # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /luansq.github.io/

# User settings
username: Luan Quaresma
user_description: Olá me chamo Luan Quaresma e esse é o meu CV online. Graduação em Ciência da Computação na Estácio|CEUT.
user_title: Cientista da computação. 
email: luansoares2010@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: 
# facebook_username: 
linkedin_username: luanfour
github_username:  luanfour
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
