# Site settings
title: Luan S. Quaresma
description: Luan Quaresma
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Luan S. Quaresma
user_description: Olá! Sou o Luan S. Quaresma, formado em Ciência da Computação na faculdade Estácio - CEUT. Tenho paixão por tecnologia e como ajudar tanto a rotina cotidiano pessoal e profissional. Estou compartilhando minha experiencia e conhecimento nesse CV online.  Entrei no mercado de trabalho como Aux. de estoque e promovido para Aux de Suporte tecnico PL, atualmente estou em expansão de conhecimentos em infraestrutura, monitoriamento e segurança.
user_title: Computer Scientist
email: luansoares2010@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: 
# facebook_username: 
linkedin_username: luanfour
github_username:  luanfour
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
